import mongoose from 'mongoose';
import { Medication } from '../models/Medication.js';
import { MedicationLog } from '../models/MedicationLog.js';
import { DoseLog } from '../models/DoseLog.js';
import { isDoseLevelEnabled } from '../config/features.js';
import { MS_PER_DAY } from '../utils/adherenceRange.js';

/** Mongo expression: UTC midnight for a given datetime field (use as $$ROOT.datetime in some contexts). */
export const doseLogUtcDayStartExpr = {
  $dateFromParts: {
    year: { $year: { date: '$datetime', timezone: 'UTC' } },
    month: { $month: { date: '$datetime', timezone: 'UTC' } },
    day: { $dayOfMonth: { date: '$datetime', timezone: 'UTC' } },
    hour: 0,
    minute: 0,
    second: 0,
    millisecond: 0,
    timezone: 'UTC',
  },
};

export function utcDayEndExclusive(dayStart) {
  return new Date(dayStart.getTime() + MS_PER_DAY);
}

/**
 * Whether the user has any adherence record for this medication on this UTC calendar day.
 * Dose-level mode: any DoseLog in [day, day+1). Legacy: MedicationLog for that date.
 */
export async function hasLoggedMedicationDay(userId, medicationId, dayUtc) {
  const uid = typeof userId === 'string' ? new mongoose.Types.ObjectId(userId) : userId;
  const mid = typeof medicationId === 'string' ? new mongoose.Types.ObjectId(medicationId) : medicationId;
  const end = utcDayEndExclusive(dayUtc);

  if (isDoseLevelEnabled()) {
    const hit = await DoseLog.findOne({
      userId: uid,
      medicationId: mid,
      datetime: { $gte: dayUtc, $lt: end },
    })
      .select('_id')
      .lean();
    return !!hit;
  }

  const hit = await MedicationLog.findOne({
    userId: uid,
    medicationId: mid,
    date: dayUtc,
  })
    .select('_id')
    .lean();
  return !!hit;
}

/**
 * Remove legacy daily rollup DoseLog rows for this med+UTC day (before replacing via POST /api/logs).
 */
export async function deleteLegacyDailyRollups(userId, medicationId, dayUtc) {
  const end = utcDayEndExclusive(dayUtc);
  await DoseLog.deleteMany({
    userId,
    medicationId,
    legacyDailyRollup: true,
    datetime: { $gte: dayUtc, $lt: end },
  });
}

/**
 * True if this UTC day has any granular (non–daily-rollup) dose events for this medication.
 */
export async function hasGranularDosesForDay(userId, medicationId, dayUtc) {
  const end = utcDayEndExclusive(dayUtc);
  const hit = await DoseLog.findOne({
    userId,
    medicationId,
    legacyDailyRollup: { $ne: true },
    datetime: { $gte: dayUtc, $lt: end },
  })
    .select('_id')
    .lean();
  return !!hit;
}

/**
 * Daily-shaped rollup from DoseLog (one row per user+med+UTC day): taken if any taken that day.
 * @param {{ limit?: number, dayStart?: Date }} options — optional filter to one UTC calendar day, max rows.
 */
export async function aggregateUserDoseLogsAsDailyRollup(userId, options = {}) {
  const { limit = null, dayStart = null } = options;
  const oid = new mongoose.Types.ObjectId(userId);

  const pipeline = [
    { $match: { userId: oid } },
    { $addFields: { dayStart: doseLogUtcDayStartExpr } },
  ];
  if (dayStart) {
    pipeline.push({ $match: { dayStart } });
  }
  pipeline.push(
    { $sort: { datetime: -1 } },
    {
      $group: {
        _id: { med: '$medicationId', day: '$dayStart' },
        hasTaken: { $max: { $cond: [{ $eq: ['$status', 'taken'] }, 1, 0] } },
        anyAuto: { $max: { $cond: ['$autoGenerated', 1, 0] } },
        rowId: { $first: '$_id' },
      },
    },
    {
      $project: {
        _id: '$rowId',
        userId: oid,
        medicationId: '$_id.med',
        date: '$_id.day',
        status: { $cond: [{ $eq: ['$hasTaken', 1] }, 'taken', 'missed'] },
        autoGenerated: { $eq: ['$anyAuto', 1] },
      },
    },
    {
      $lookup: {
        from: Medication.collection.name,
        localField: 'medicationId',
        foreignField: '_id',
        as: 'medicationId',
      },
    },
    { $unwind: '$medicationId' },
    { $sort: { date: -1, medicationId: 1 } }
  );
  if (limit != null) {
    pipeline.push({ $limit: limit });
  }
  return DoseLog.aggregate(pipeline);
}
