import { Medication } from '../models/Medication.js';
import { MedicationLog, startOfUtcDay } from '../models/MedicationLog.js';
import { DoseLog } from '../models/DoseLog.js';
import { isDoseLevelEnabled } from '../config/features.js';
import { hasLoggedMedicationDay } from './adherenceLogBridge.js';
import { MS_PER_DAY } from '../utils/adherenceRange.js';

const INTERVAL_MS = 5 * 60 * 1000;

/**
 * Parse "HH:mm" to minutes since UTC midnight. Invalid → null.
 */
function slotToUtcMinutes(slot) {
  const s = String(slot).trim();
  const m = /^(\d{1,2}):(\d{2})$/.exec(s);
  if (!m) return null;
  const h = Number(m[1]);
  const min = Number(m[2]);
  if (h > 23 || min > 59) return null;
  return h * 60 + min;
}

function nowUtcMinutesSinceMidnight() {
  const n = new Date();
  return n.getUTCHours() * 60 + n.getUTCMinutes();
}

/** Medication active on ref UTC calendar day (inclusive start/end days). */
function isMedicationActiveOnDay(med, refDayStart) {
  const t = refDayStart.getTime();
  const start = med.startDate ? startOfUtcDay(med.startDate)?.getTime() : null;
  const end = med.endDate ? startOfUtcDay(med.endDate)?.getTime() : null;
  if (start != null && t < start) return false;
  if (end != null && t > end) return false;
  return true;
}

/**
 * True when every schedule slot's UTC time is strictly before "now" (minute resolution).
 * Matches one-log-per-day model: we only auto-mark missed after the last expected dose time has passed.
 */
function allScheduleSlotsPassedUtc(schedule, nowMinutes) {
  if (!Array.isArray(schedule) || schedule.length === 0) return false;
  const minutes = schedule.map(slotToUtcMinutes).filter((x) => x != null);
  if (minutes.length === 0) return false;
  return minutes.every((slotM) => nowMinutes > slotM);
}

/**
 * Insert missed log if missing. Never updates existing rows.
 */
async function ensureAutoMissedForMedication(med, todayUtc) {
  const existing = await hasLoggedMedicationDay(med.userId, med._id, todayUtc);
  if (existing) return;

  if (isDoseLevelEnabled()) {
    try {
      await DoseLog.create({
        userId: med.userId,
        medicationId: med._id,
        datetime: new Date(todayUtc.getTime() + MS_PER_DAY - 1),
        status: 'missed',
        autoGenerated: true,
        legacyDailyRollup: false,
      });
    } catch (err) {
      if (err.code === 11000) return;
      throw err;
    }
    return;
  }

  try {
    await MedicationLog.create({
      userId: med.userId,
      medicationId: med._id,
      date: todayUtc,
      status: 'missed',
      autoGenerated: true,
    });
  } catch (err) {
    if (err.code === 11000) return;
    throw err;
  }
}

/**
 * One sweep: for each medication with a schedule, if active today and all slots have passed UTC
 * and there is no log for today, insert auto missed.
 */
export async function runAutoMissedDoseSweep() {
  const todayUtc = startOfUtcDay(new Date());
  if (!todayUtc) return;

  const nowM = nowUtcMinutesSinceMidnight();

  const medications = await Medication.find({ 'schedule.0': { $exists: true } }).lean();

  for (const med of medications) {
    if (!isMedicationActiveOnDay(med, todayUtc)) continue;
    if (!allScheduleSlotsPassedUtc(med.schedule, nowM)) continue;
    await ensureAutoMissedForMedication(med, todayUtc);
  }
}

let intervalId = null;

function clearAutoMissedInterval() {
  if (intervalId != null) {
    clearInterval(intervalId);
    intervalId = null;
  }
}

/**
 * Starts a 5-minute interval (plus one immediate run). Returns stop function (idempotent).
 */
export function startAutoMissedDoseJob() {
  if (intervalId != null) {
    return clearAutoMissedInterval;
  }

  runAutoMissedDoseSweep().catch((err) => {
    console.error('[autoMissedDose] initial sweep failed:', err.message);
  });

  intervalId = setInterval(() => {
    runAutoMissedDoseSweep().catch((err) => {
      console.error('[autoMissedDose] sweep failed:', err.message);
    });
  }, INTERVAL_MS);

  return clearAutoMissedInterval;
}
