import mongoose from 'mongoose';
import { Medication } from '../models/Medication.js';
import { DoseLog } from '../models/DoseLog.js';
import { startOfUtcDay } from '../models/MedicationLog.js';
import { isDoseLevelEnabled } from '../config/features.js';
import { deleteLegacyDailyRollups } from '../services/adherenceLogBridge.js';
import { emitUserDataChanged } from '../realtime/socketHub.js';

function formatDoseLog(doc) {
  const o = doc.toObject ? doc.toObject() : { ...doc };
  return {
    id: o._id,
    userId: o.userId,
    medicationId: o.medicationId,
    datetime: o.datetime,
    status: o.status,
    createdAt: o.createdAt,
    updatedAt: o.updatedAt,
  };
}

/**
 * POST /api/dose-logs — append a dose-level event (feature-flagged).
 * Clears same-day legacy daily rollup rows for that medication (POST /api/logs) so counts stay consistent.
 */
export async function createDoseLog(req, res) {
  if (!isDoseLevelEnabled()) {
    return res.status(403).json({
      message: 'Dose-level logging is disabled (set USE_DOSE_LEVEL=true to enable).',
      code: 'DOSE_LEVEL_DISABLED',
    });
  }

  try {
    const userId = req.user.id;
    const { medicationId, datetime: datetimeInput, status } = req.body;

    if (!medicationId) {
      return res.status(400).json({ message: 'medicationId is required' });
    }
    if (!mongoose.isValidObjectId(medicationId)) {
      return res.status(400).json({ message: 'Invalid medicationId' });
    }
    if (status !== 'taken' && status !== 'missed') {
      return res.status(400).json({ message: 'status must be "taken" or "missed"' });
    }
    if (datetimeInput == null || datetimeInput === '') {
      return res.status(400).json({ message: 'datetime is required' });
    }

    const at = new Date(datetimeInput);
    if (Number.isNaN(at.getTime())) {
      return res.status(400).json({ message: 'Invalid datetime' });
    }

    const med = await Medication.findOne({ _id: medicationId, userId });
    if (!med) {
      return res.status(404).json({ message: 'Medication not found' });
    }

    const day = startOfUtcDay(at);
    if (day) {
      await deleteLegacyDailyRollups(userId, medicationId, day);
    }

    const created = await DoseLog.create({
      userId,
      medicationId,
      datetime: at,
      status,
      legacyDailyRollup: false,
      autoGenerated: false,
    });

    emitUserDataChanged(userId);
    return res.status(201).json({ doseLog: formatDoseLog(created) });
  } catch (err) {
    if (err.name === 'ValidationError') {
      const first = Object.values(err.errors || {})[0];
      return res.status(400).json({ message: first?.message || 'Validation failed' });
    }
    console.error('createDoseLog error:', err);
    return res.status(500).json({ message: 'Server error while saving dose log' });
  }
}
