import mongoose from 'mongoose';
import { Medication } from '../models/Medication.js';
import { MedicationLog, startOfUtcDay } from '../models/MedicationLog.js';
import { DoseLog } from '../models/DoseLog.js';
import { isDoseLevelEnabled } from '../config/features.js';
import {
  aggregateUserDoseLogsAsDailyRollup,
  deleteLegacyDailyRollups,
  hasGranularDosesForDay,
} from '../services/adherenceLogBridge.js';

/**
 * Shape a log document for JSON (optional medication summary).
 */
export function formatLog(doc) {
  const o = doc.toObject ? doc.toObject() : { ...doc };
  const med = o.medicationId;
  const base = {
    id: o._id,
    userId: o.userId,
    medicationId: med && med._id ? med._id : o.medicationId,
    date: o.date,
    status: o.status,
    ...(o.autoGenerated ? { autoGenerated: true } : {}),
  };
  if (med && typeof med === 'object' && med.name !== undefined) {
    base.medication = {
      id: med._id,
      name: med.name,
      dosage: med.dosage ?? '',
    };
  }
  return base;
}

/**
 * POST /api/logs — upsert log for (user, medication, calendar day). Default day is today (UTC).
 */
export async function upsertTodayLog(req, res) {
  try {
    const userId = req.user.id;
    const { medicationId, status, date: dateInput } = req.body;

    if (!medicationId) {
      return res.status(400).json({ message: 'medicationId is required' });
    }
    if (!mongoose.isValidObjectId(medicationId)) {
      return res.status(400).json({ message: 'Invalid medicationId' });
    }
    if (status !== 'taken' && status !== 'missed') {
      return res.status(400).json({ message: 'status must be "taken" or "missed"' });
    }

    const med = await Medication.findOne({ _id: medicationId, userId });
    if (!med) {
      return res.status(404).json({ message: 'Medication not found' });
    }

    const day =
      dateInput != null && dateInput !== ''
        ? startOfUtcDay(dateInput)
        : startOfUtcDay(new Date());

    if (!day) {
      return res.status(400).json({ message: 'Invalid date' });
    }

    if (isDoseLevelEnabled()) {
      const granular = await hasGranularDosesForDay(userId, medicationId, day);
      if (granular) {
        return res.status(409).json({
          message:
            'This day already has dose-level events. Use POST /api/dose-logs, or remove them before using daily log.',
          code: 'DOSE_LEVEL_CONFLICT',
        });
      }

      await deleteLegacyDailyRollups(userId, medicationId, day);

      const created = await DoseLog.create({
        userId,
        medicationId,
        datetime: new Date(day.getTime() + 12 * 60 * 60 * 1000),
        status,
        legacyDailyRollup: true,
        autoGenerated: false,
      });

      const populated = await DoseLog.findById(created._id)
        .populate('medicationId', 'name dosage')
        .lean();

      return res.status(200).json({
        log: formatLog({ ...populated, date: day }),
      });
    }

    const log = await MedicationLog.findOneAndUpdate(
      { userId, medicationId, date: day },
      {
        $set: { status, autoGenerated: false },
        $setOnInsert: { userId, medicationId, date: day },
      },
      { new: true, upsert: true, runValidators: true }
    ).populate('medicationId', 'name dosage');

    return res.status(200).json({ log: formatLog(log) });
  } catch (err) {
    if (err.code === 11000) {
      return res.status(409).json({ message: 'A log already exists for this medication and day' });
    }
    if (err.name === 'ValidationError') {
      const messages = Object.values(err.errors || {}).map((e) => e.message);
      return res.status(400).json({ message: messages[0] || 'Validation failed' });
    }
    console.error('upsertTodayLog error:', err);
    return res.status(500).json({ message: 'Server error while saving log' });
  }
}

/**
 * GET /api/logs — all logs for the authenticated user.
 */
export async function getUserLogs(req, res) {
  try {
    const userId = req.user.id;

    if (isDoseLevelEnabled()) {
      const rolled = await aggregateUserDoseLogsAsDailyRollup(userId);
      const formatted = rolled.map((row) => formatLog(row));
      return res.json({ logs: formatted });
    }

    const logs = await MedicationLog.find({ userId })
      .populate('medicationId', 'name dosage')
      .sort({ date: -1, medicationId: 1 })
      .lean();

    const formatted = logs.map((row) => formatLog(row));
    return res.json({ logs: formatted });
  } catch (err) {
    console.error('getUserLogs error:', err);
    return res.status(500).json({ message: 'Server error while fetching logs' });
  }
}
