import mongoose from 'mongoose';

const statusEnum = ['taken', 'missed'];

/**
 * Per-dose event (point-in-time). Separate from MedicationLog (one row per user/med/calendar day).
 * Safe to deploy before consumers exist: new collection, no migration of legacy data.
 */
const doseLogSchema = new mongoose.Schema(
  {
    userId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      required: [true, 'User is required'],
      index: true,
    },
    medicationId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Medication',
      required: [true, 'Medication is required'],
      index: true,
    },
    datetime: {
      type: Date,
      required: [true, 'datetime is required'],
    },
    status: {
      type: String,
      enum: statusEnum,
      required: [true, 'Status is required'],
    },
    /** One row per med+day from POST /api/logs when dose-level mode is on (replaced on each upsert). */
    legacyDailyRollup: {
      type: Boolean,
      default: false,
    },
    /** Created by auto-missed background job. */
    autoGenerated: {
      type: Boolean,
      default: false,
    },
  },
  { timestamps: true }
);

doseLogSchema.index({ userId: 1, datetime: -1 });
doseLogSchema.index({ userId: 1, medicationId: 1, datetime: -1 });

export const DoseLog = mongoose.model('DoseLog', doseLogSchema);
export const DOSE_LOG_STATUS_VALUES = statusEnum;
