import mongoose from 'mongoose';

const statusEnum = ['taken', 'missed'];

/** Normalize to UTC midnight for stable per-day uniqueness */
export function startOfUtcDay(input) {
  const d = input instanceof Date ? input : new Date(input);
  if (Number.isNaN(d.getTime())) return null;
  return new Date(Date.UTC(d.getUTCFullYear(), d.getUTCMonth(), d.getUTCDate()));
}

/**
 * One adherence record per user + medication + calendar day (date stored as UTC midnight).
 */
const medicationLogSchema = new mongoose.Schema(
  {
    userId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      required: [true, 'User is required'],
    },
    medicationId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Medication',
      required: [true, 'Medication is required'],
    },
    date: {
      type: Date,
      required: [true, 'Date is required'],
      default: () => startOfUtcDay(new Date()),
    },
    status: {
      type: String,
      enum: statusEnum,
      required: [true, 'Status is required'],
    },
    /** Set when row was created by the auto-missed background job (manual logs omit or false). */
    autoGenerated: {
      type: Boolean,
      default: false,
    },
  },
  { timestamps: false }
);

medicationLogSchema.index({ userId: 1, medicationId: 1, date: 1 }, { unique: true });
/** Range queries for analytics (userId + date window) */
medicationLogSchema.index({ userId: 1, date: 1 });

export const MedicationLog = mongoose.model('MedicationLog', medicationLogSchema);
